/**
 * Lowercase substrings — if any appear in narrator output, guardrails fail.
 * Curated active / well-known MLB full names (approx. 200) to keep kids' mode clean.
 */
export const MLB_PLAYER_DENY_SUBSTRINGS: string[] = [
  "aaron judge",
  "shohei ohtani",
  "mookie betts",
  "juan soto",
  "ronald acuña",
  "ronald acuna",
  "fernando tatís",
  "fernando tatis",
  "vladimir guerrero jr",
  "bo bichette",
  "corey seager",
  "marcus semien",
  "jose altuve",
  "yordan alvarez",
  "kyle tucker",
  "alex bregman",
  "francisco lindor",
  "pete alonso",
  "jacob degrom",
  "max scherzer",
  "justin verlander",
  "clayton kershaw",
  "mike trout",
  "bryce harper",
  "trea turner",
  "freddie freeman",
  "manny machado",
  "xander bogaerts",
  "rafael devers",
  "carlos correa",
  "byron buxton",
  "carlos rodón",
  "carlos rodon",
  "gerrit cole",
  "aaron nola",
  "zack wheeler",
  "spencer strider",
  "matt olson",
  "austin riley",
  "corbin carroll",
  "ketel marte",
  "paul goldschmidt",
  "nolan arenado",
  "willson contreras",
  "salvador perez",
  "bobby witt jr",
  "julio rodríguez",
  "julio rodriguez",
  "randy arozarena",
  "yandy díaz",
  "yandy diaz",
  "josh bell",
  "cody bellinger",
  "dansby swanson",
  "kyle schwarber",
  "nick castellanos",
  "bryson stott",
  "taijuan walker",
  "zach efflin",
  "blake snell",
  "logan webb",
  "will smith",
  "acuña jr",
  "acuna jr",
  "guerrero jr",
  "de grom",
  "degrom",
  "scherzer",
  "verlander",
  "kershaw",
  "ohtani the",
  "judge's",
  "soto's",
  "trout's",
  "harper's",
  "betts'",
  "lindor's",
  "alonso's",
  "alvarez's",
  "tucker's",
  "freeman's",
  "machado's",
  "turner's",
  "strider's",
  "carroll's",
  "arenado's",
  "goldschmidt's",
  "rodríguez's",
  "rodriguez's",
  "arozarena's",
  "bellinger's",
  "bogaerts'",
  "devers'",
  "semien's",
  "seager's",
  "bichette's",
  "guerrero's",
  "witt jr",
  "contreras",
  "perez's",
  "altuve's",
  "bregman's",
  "yelich",
  "christian yelich",
  "william contreras",
  "will smith catcher",
  "jazz chisholm",
  "oneil cruz",
  "o'neil cruz",
  "elly de la cruz",
  "gunner henderson",
  "gunnar henderson",
  "adley rutschman",
  "corbin burnes",
  "dylan cease",
  "pablo lópez",
  "pablo lopez",
  "george kirby",
  "luis castillo",
  "logan gilbert",
  "framber valdez",
  "cristian javier",
  "hunter brown",
  "jose urquidy",
  "ryan pressly",
  "devin williams",
  "josh hader",
  "emmanuel clase",
  "clase",
  "clay holmes",
  "david bednar",
  "camilo doval",
  "andres muñoz",
  "andres munoz",
  "edwin díaz",
  "edwin diaz",
  "jhoan duran",
  "felix bautista",
  "jordan romano",
  "ryan helsley",
  "paul skenes",
  "paul skenes",
  "jackson holliday",
  "wyatt langford",
  "evan carter",
  "josh jung",
  "corey seager's",
  "marcus stroman",
  "sonny gray",
  "pablo lopez",
  "kevin gausman",
  "chris sale",
  "tyler glasnow",
  "shane mcclanahan",
  "jeff mcneil",
  "brandon nimmo",
  "starling marte",
  "francisco alvarez",
  "mark vientos",
  "brett baty",
  "eddie rosario",
  "michael harris ii",
  "sean murphy",
  "travis d'arnaud",
  "marcell ozuna",
  "ozzie albies",
  "michael conforto",
  "jorge soler",
  "luis robert jr",
  "luis robert",
  "andrew benintendi",
  "eloy jiménez",
  "eloy jimenez",
  "dylan cease",
  "tarik skubal",
  "riley greene",
  "spencer torkelson",
  "jack flaherty",
  "jordan walker",
  "nolan gorman",
  "willson contreras",
  "alec burleson",
  "masyn winn",
  "victor scott ii",
  "ivan herrera",
  "ryan jeffers",
  "royce lewis",
  "carlos santana",
  "byron buxton's",
  "max kepler",
  "edouard julien",
  "ryan mountcastle",
  "gunnar henderson's",
  "adley rutschman's",
  "anthony santander",
  "cedric mullins",
  "austin hays",
  "kyle bradish",
  "grayson rodriguez",
  "john means",
  "dean kremer",
  "kyle gibson",
  "craig kimbrel",
  "jacob stallings",
  "j.t. realmuto",
  "jt realmuto",
  "bryce harper's",
  "kyle schwarber's",
  "nick castellanos's",
  "trea turner's",
  "brandon marsh",
  "johan rojas",
  "cristopher sánchez",
  "cristopher sanchez",
  "ranger suárez",
  "ranger suarez",
  "zack wheeler's",
  "aaron nola's",
  "jose alvarado",
  "gregory soto",
  "seranthony domínguez",
  "seranthony dominguez",
  "jeff hoffman",
  "matt strahm",
  "orion kerking",
  "kerking",
];
